export function normalizeClientItem(item) {
  return {
    ...item,
    isAvailable: item?.isAvailable !== false,
  };
}

export function normalizeStoredArray(value) {
  return Array.isArray(value) ? value : [];
}

export function normalizeStoredLastOrder(value) {
  if (!value?.orderNumber || !value?.tableNumber) return null;
  return value;
}

export const DEFAULT_COFFEE_ITEMS = [
  {
    id: 1,
    name: 'Velvet Cappuccino',
    subtitle: 'Dark Chocolate & Vanilla Bean',
    description: 'Luxurious espresso blend with velvety steamed milk, artisan dark chocolate, and Madagascar vanilla',
    price: 20.0,
    originalPrice: null,
    rating: 4.9,
    reviews: 1247,
    image: 'https://images.unsplash.com/photo-1572442388796-11668a67e53d?w=800&h=600&fit=crop&q=90',
    isPopular: true,
    isTrending: true,
    isNew: false,
    calories: 180,
    prepTime: '4 min',
    badge: '🔥 Trending',
    tags: ['Signature', 'Sweet', 'Creamy'],
    isAvailable: true,
  },
  {
    id: 2,
    name: 'Golden Oat Latte',
    subtitle: 'Turmeric & Honey Infusion',
    description: 'Creamy oat milk latte with golden turmeric, raw honey, and a hint of cinnamon',
    price: 18.0,
    originalPrice: null,
    rating: 4.8,
    reviews: 892,
    image: 'https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=800&h=600&fit=crop&q=90',
    isPopular: false,
    isTrending: false,
    isNew: true,
    calories: 150,
    prepTime: '3 min',
    badge: '✨ New',
    tags: ['Vegan', 'Healthy', 'Unique'],
    isAvailable: true,
  },
  {
    id: 3,
    name: 'Midnight Espresso',
    subtitle: 'Single Origin Ethiopian',
    description: 'Intense double shot from Ethiopian highlands with notes of dark chocolate and wild berries',
    price: 13.0,
    originalPrice: null,
    rating: 5.0,
    reviews: 2156,
    image: 'https://images.unsplash.com/photo-1510591509098-f4fdc6d0ff04?w=800&h=600&fit=crop&q=90',
    isPopular: true,
    isTrending: false,
    isNew: false,
    calories: 5,
    prepTime: '2 min',
    badge: '⭐ Top Rated',
    tags: ['Strong', 'Bold', 'Premium'],
    isAvailable: true,
  },
  {
    id: 4,
    name: 'Cloud Nine Latte',
    subtitle: 'Brown Butter & Sea Salt Caramel',
    description: 'Silky smooth latte with house-made brown butter caramel and Himalayan pink salt',
    price: 21.5,
    originalPrice: 23.5,
    rating: 4.9,
    reviews: 1543,
    image: 'https://images.unsplash.com/photo-1534778101976-62847782c213?w=800&h=600&fit=crop&q=90',
    isPopular: true,
    isTrending: true,
    isNew: false,
    calories: 220,
    prepTime: '5 min',
    badge: '🏆 Award Winner',
    tags: ['Signature', 'Sweet', 'Artisan'],
    isAvailable: true,
  },
  {
    id: 5,
    name: 'Rose Garden Latte',
    subtitle: 'Rose Petals & White Chocolate',
    description: 'Delicate latte infused with organic rose petals and creamy Belgian white chocolate',
    price: 22.5,
    originalPrice: null,
    rating: 4.7,
    reviews: 678,
    image: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=800&h=600&fit=crop&q=90',
    isPopular: false,
    isTrending: true,
    isNew: true,
    calories: 195,
    prepTime: '4 min',
    badge: '💐 Limited Edition',
    tags: ['Floral', 'Sweet', 'Instagram-Worthy'],
    isAvailable: true,
  },
  {
    id: 6,
    name: 'Midnight Mocha',
    subtitle: 'Dark Chocolate & Espresso Fusion',
    description: 'Decadent mocha with 70% dark chocolate, double espresso, and hand-whipped vanilla cream',
    price: 21.0,
    originalPrice: 24.0,
    rating: 4.9,
    reviews: 1891,
    image: 'https://images.unsplash.com/photo-1578374173705-0cae7ebaf74e?w=800&h=600&fit=crop&q=90',
    isPopular: true,
    isTrending: false,
    isNew: false,
    calories: 280,
    prepTime: '5 min',
    badge: '💎 Premium',
    tags: ['Rich', 'Chocolate', 'Indulgent'],
    isAvailable: true,
  },
  {
    id: 7,
    name: 'Matcha Cloud',
    subtitle: 'Japanese Ceremonial Grade',
    description: 'Premium ceremonial matcha with oat milk foam and a touch of agave',
    price: 19.0,
    originalPrice: null,
    rating: 4.8,
    reviews: 756,
    image: 'https://images.unsplash.com/photo-1569825201748-e15f8c4f3adf?w=800&h=600&fit=crop&q=90',
    isPopular: false,
    isTrending: true,
    isNew: true,
    calories: 120,
    prepTime: '3 min',
    badge: '🍃 Wellness',
    tags: ['Healthy', 'Energizing', 'Vegan'],
    isAvailable: true,
  },
  {
    id: 8,
    name: 'Iced Caramel Macchiato',
    subtitle: 'Cold Foam Perfection',
    description: 'Layered iced espresso with vanilla, caramel drizzle, and cold foam',
    price: 18.5,
    originalPrice: null,
    rating: 4.7,
    reviews: 1123,
    image: 'https://images.unsplash.com/photo-1517487881594-2787fef5ebf7?w=800&h=600&fit=crop&q=90',
    isPopular: true,
    isTrending: false,
    isNew: false,
    calories: 210,
    prepTime: '4 min',
    badge: '❄️ Refreshing',
    tags: ['Iced', 'Sweet', 'Popular'],
    isAvailable: true,
  },
];
